import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.25"

[font]
size = 10

[font.bold]
family = "Hasklug Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hasklug Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hasklug Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B[1;2P"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;2Q"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;2R"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[1;2S"
key = "Key4"
mods = "Control"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
